name: NodeCI
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 6
          registry-url: "https://registry.npmjs.org/"
      - name: Publish to NPMJS
        run: |
          npm install
          npm test
          npm config set //registry.npmjs.org/:_authToken=${{secrets.GPR_TOKEN}}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 6
          registry-url: https://npm.pkg.github.com/
          scope: "@oskang09"
      - name: Publish to GPR
        run: |
          npm install
          npm test
          npm config set //registry.npmjs.org/:_authToken=${{secrets.GPR_TOKEN}}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
      - name: Build
        run: |
          npm install
          npm test
